repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: '\S*.py$'
        args: ["--count", "--statistics", "--ignore=E731,E501"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: '\S*.py$'
