repos:
  - repo: https://github.com/pycqa/flake8
    hooks:
      - id: flake
        files: '.*\.py$'
        args: ["--count", "--statistics"]
  - repo: https://github.com/psf/black
    hooks:
      - id: black
        files: '.*\.py$'
